import type { AppProps, AppType } from "next/app";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import Head from "next/head";
import { Analytics } from "@vercel/analytics/react";
import { useEffect } from "react";

const MyApp: AppType = ({ Component, pageProps }: AppProps) => {
  useEffect(() => {
    window.document.documentElement.classList.add("dark");
  }, []);

  return (
    <ClerkProvider {...pageProps}>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster position="bottom-center" />
      <Component {...pageProps} />

      <Analytics />
    </ClerkProvider>
  );
};

export default api.withTRPC(MyApp);
